### ISSUE TITLE
Optim not working using SplitTable with no updateGradInput method

### ISSUE THREAD

**Issue by aleSuglia** [torch/optim#104]
Hi there,

I'm using Torch to implement **TransE** model. Actually I need to use a *SplitTable* and I got an error like the one reported here: https://github.com/torch/nn/issues/568. I've tried to redefine the *updateGradInput* method but using **optim** I got the following error in the backward pass: 
```
/opt/torch/install/bin/luajit: /opt/torch/install/share/lua/5.1/optim/sgd.lua:82: inconsistent tensor size at /opt/torch/pkg/torch/lib/TH/generic/THTensorMath.c:500
stack traceback:
        [C]: in function 'add'
        /opt/torch/install/share/lua/5.1/optim/sgd.lua:82: in function 'optim_method'
```
I've tried my model using the *on the fly* training procedure and it works. So I think that the problem is related to *optim*; maybe it is not able to manage the weird case of the undefined *updateGradInput* method in the *SplitTable*.
 
Thank you for your help.

Alessandro

**Comment by soumith** [comment]
if you could give a small reproduction, i will take a look. From this info, I've thought it through and I cant figure out what the issue is.
