### ISSUE TITLE
module 'optim' not found 

### ISSUE THREAD

**Issue by Sherriiie** [torch/optim#107]
I have installed optim, but it could not be found. 
`lua: ./Network.lua:1: module 'optim' not found:
	no field package.preload['optim']
	no file '/usr/local/share/lua/5.2/optim.lua'
	no file '/usr/local/share/lua/5.2/optim/init.lua'
	no file '/usr/local/lib/lua/5.2/optim.lua'
	no file '/usr/local/lib/lua/5.2/optim/init.lua'
	no file '/usr/share/lua/5.2/optim.lua'
	no file '/usr/share/lua/5.2/optim/init.lua'
	no file './optim.lua'
	no file '/usr/local/lib/lua/5.2/optim.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/optim.so'
	no file '/usr/lib/lua/5.2/optim.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './optim.so'
stack traceback:
	[C]: in function 'require'
	./Network.lua:1: in main chunk
	[C]: in function 'require'
	./AN4CTCTest.lua:4: in main chunk
	[C]: in ?
`
The installing information is following:
`sherrie@sherrie-PC:~/CTCSR$ luarocks install optim
Installing https://raw.githubusercontent.com/torch/rocks/master/optim-1.0.5-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/optim-1.0.5-0.rockspec... switching to 'build' mode
正克隆到 'optim'...
remote: Counting objects: 50, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 50 (delta 10), reused 22 (delta 6), pack-reused 0
接收对象中: 100% (50/50), 40.67 KiB | 0 bytes/s, done.
处理 delta 中: 100% (10/10), done.
检查连接... 完成。
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/sherrie/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0" && make
   
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/sherrie/torch/install
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_optim-1.0.5-0-9983/optim/build
cd build && make install
Install the project...
-- Install configuration: "Release"
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/checkgrad.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adagrad.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adadelta.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/polyinterp.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/rmsprop.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/lswolfe.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/nag.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adam.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/rprop.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/init.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/cg.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/sgd.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/fista.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adamax.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/asgd.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/lbfgs.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/Logger.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/ConfusionMatrix.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/cmaes.lua
Updating manifest for /home/sherrie/torch/install/lib/luarocks/rocks
optim 1.0.5-0 is now built and installed in /home/sherrie/torch/install/ (license: BSD)
`
Could you help me about this error?

**Comment by szagoruyko** [comment]
seems that you're using system lua. try starting torch interpreter with `th`

**Comment by Sherriiie** [comment]
yes, I use `th` for torch interpreter and the error disappears. Thanks.
