### ISSUE TITLE
Issue with rmsprop

### ISSUE THREAD

**Issue by 1adrianb** [torch/optim#109]
While training with sgd works fine for the exact architecture, rmsprop throws the fallowing error:

```
qlua: /home/psxab5/torch/install/share/lua/5.1/optim/rmsprop.lua:49: calling 'addcmul' on bad self (sizes do not match at /tmp/luarocks_cutorch-scm-1-4946/cutorch/lib/THC/THCTensorMath.cu:231)
stack traceback:
        [C]: at 0x7fcea4fe4e20
        [C]: in function 'addcmul'
        /home/psxab5/torch/install/share/lua/5.1/optim/rmsprop.lua:49: in function 'rmsprop'
        ./train.lua:62: in function 'train'
        main.lua:91: in main chunk
```

**Comment by soumith** [comment]
Hi, i need a few more details or a script to reproduce this behavior to help fix this.

**Comment by gulvarol** [comment]
In case this is helpful to someone else, I was stuck with the same issue and then realized that I was loading my old optimState to continue training a model with an additional layer at the end, which changed its number of parameters. The following line would of course break with different sizes for state.m and dfdx.
 `  state.m:addcmul(1.0-alpha, dfdx, dfdx)`
I simply re-initialized the state, I don't know if there is a better option.

**Comment by soumith** [comment]
there isn't a better option, you would have to re-initialize the state. 
you could add assertions that the number of parameters / gradparameters remains the same...
