### ISSUE TITLE
ConfusionMatrix:batchAdd error in function indexAdd

### ISSUE THREAD

**Issue by jessika0991** [torch/optim#116]
Hello,

I would like to plot the confusion matrix for the resnet network https://github.com/facebook/fb.resnet.torch. I substitute the 1000-way classifier with a binary one. 
My output is a tensor of size 32x2 and my target a tensor of size 32x1.

When I try to use ConfusionMatrix:batchAdd I get this error:

/home/jessica/torch/install/bin/luajit: ...ca/torch/install/share/lua/5.1/optim/ConfusionMatrix.lua:117: bad argument #1 to 'indexAdd' (out of range at /home/jessica/torch/pkg/torch/lib/TH/generic/THTensor.c:729)
stack traceback:
	[C]: in function 'indexAdd'
	...ca/torch/install/share/lua/5.1/optim/ConfusionMatrix.lua:117: in function 'batchAdd'
	./train.lua:71: in function 'train'
	main.lua:59: in main chunk
	[C]: in function 'dofile'
	...sica/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

Given that i am new to torch and lua. Could help me understanding what is going wrong? Thank you

**Comment by soumith** [comment]
looking at the code, it looks like you are giving an index to indexAdd that is > 1000 or < 1 (maybe you have zero indices)
