### ISSUE TITLE
Question on rmsprop implementation

### ISSUE THREAD

**Issue by syoungbaak** [torch/optim#149]
According to Tensorflow implementation, it seems to me that the 53rd line of 'rmsprop.lua' needs to modified as 

state.tmp:sqrt(state.m):add(epsilon) --> state.tmp:sqrt(state.m+epsilon)

Is it okay to use the original one without modification when I try to train Inception-resnet v2 from the scratch uisng the same optimization parameters ?

**Comment by alirezag** [comment]
This is just a dampening factor, you can get approximately similar behavior if you use epsilon = sqrt(tensorflow_epsilon)
