### ISSUE TITLE
Feature request: Don't show plot window in Logger

### ISSUE THREAD

**Issue by mys007** [torch/optim#40]
Currently, `Logger:plot(...)` always displays a plot window and optionally writes to a file, i.e. it's not possible to save a plot without displaying it. This might be inconvenient if running a batch of experiments, for example. I suggest introducing a new member variable `self.showPlot = true` to control the behaviour.

**Comment by fmassa** [comment]
This has been addressed in https://github.com/torch/optim/pull/62
