### ISSUE TITLE
Plot Confusion Matrix Using iTorch

### ISSUE THREAD

**Issue by ssakhavi** [torch/optim#44]
I noticed the current configuration for plotting the confusion matrix is based on qt

Is it possible to plot the same in iTorch?

**Comment by nicholas-leonard** [comment]
![itorch](https://cloud.githubusercontent.com/assets/3520613/6250070/6e4fb55e-b759-11e4-8707-2c7568623d89.png) ?

**Comment by ssakhavi** [comment]
No, I meant plotting the matrix like in a grayscale way. With squares and
stuff.

On Wed, Feb 18, 2015 at 11:32 PM, Nicholas Léonard <notifications@github.com

**Comment by soumith** [comment]
This should be doable pretty easily, as the confusion matrix plotting (the
grayscale images) can also be saved to a file. will fix when i get the
time, or someone send in a PR please.

**Comment by johnmellor** [comment]
As of https://github.com/facebook/iTorch/commit/ebd9f86b1f8139ba035f8da5bd234a8f57a117bd iTorch supports QT (if qtlua is available), so this just works:

```lua
itorch.image(cm:render())
```
![image](https://cloud.githubusercontent.com/assets/563043/7798306/486973d8-02f0-11e5-9700-a25d8a9d8ae5.png)

**Comment by soumith** [comment]
nice! thanks a lot for that PR enabline qlua by default.

**Comment by nicholas-leonard** [comment]
That looks real nice.

Nicholas Léonard
917-741-7570

**Comment by thomaspurchas** [comment]
qlua support has been remove from iTorch as of [facebook/iTorch@50837](https://github.com/facebook/iTorch/commit/508370b8c926dc10413669d7f7ca320d5dd6cf8f) due to [issues](https://github.com/facebook/iTorch/issues/62) with QT and iPython.
