### ISSUE TITLE
[Feature request] Implementation of RMSProp

### ISSUE THREAD

**Issue by michael-p** [torch/optim#45]
Dear all,

are there any plans to include an implementation of RMSProp in the near future? I know that there are already several basic/toy implementations available elsewhere [1,2,3], but it would be nice to have a solid implementation included in the optim-package, making it easier to use in terms of installing additional packages etc...

Thanks,
Michael

[1] https://github.com/w-cheng/optimx/blob/master/rmsprop.lua
[2] https://github.com/y0ast/VariationalDeconvnet/blob/master/rmsprop.lua
[3] https://github.com/kaishengtai/torch-ntm/blob/master/rmsprop.lua

**Comment by jonathantompson** [comment]
Michael,

I also have an implementation of RMSProp, but in all honesty, I've gone
back to vanilla SGD (with nesterov momentum).  RMSProp requires another
O(n) memory overhead to store the running accumulation and I've found that
it needs a fair bit of tweaking every time you want to use it.  For these
two reasons I personally don't use it anymore.

Anyway, I just figured I would give my 2c.  I would be very interested to
know if others feel differently.

**Comment by michael-p** [comment]
I agree that hand-tuned SGD typically outperforms RMSProp (as well as most other adaptive methods like AdaGrad or AdaDelta) but for quick tests where I do not want to do much hyperparameter tuning my experience is that RMSProp works quite ok and is not very sensitive to the parameters used (i.e. just using the standard parameters produces good results).

As one of the strength of the optim package is that it is so easy to just try out a different optimization algorithm and see what works I think it would be a nice addition.

**Comment by soumith** [comment]
someone send in a PR for this pretty-please!

**Comment by soumith** [comment]
there's three implementations running in the wild. taming one and sending in a clean PR would be really nice.

**Comment by AjayTalati** [comment]
This python version is _quite thorough_

[https://github.com/BRML/climin/blob/master/climin/rmsprop.py](https://github.com/BRML/climin/blob/master/climin/rmsprop.py)

**Comment by koraykv** [comment]
closing this since it is already implemented/improved #57
