### ISSUE TITLE
Small logic error when ConfusionMatrix:batchAdd() is called

### ISSUE THREAD

**Issue by russellfei** [torch/optim#80]
Hi, all~

This is the real first time to use minibatch mode since I've been sticking to minibatch=1 (SGD ;-) for long time. And it  should be equivalent when call `batchAdd()` with single input and single label, but it seems there is a small bug in `batchAdd()` at [Click me ;-)](https://github.com/torch/optim/blob/07fb9e0e22c1ff1a64613b24f0ba290e710aa5bd/ConfusionMatrix.lua#L102)

***
_error case_:
for network model
```lua
net = nn.Sequential()
....
-- expected to outpout 8 predictions
net:add(nn.Reshape(8))
```
and with input and label shown below
```lua
input = torch.FloatTensor(1,4,12,12)
target = torch.FloatTensor(1,1)
```
The output data formate is `torch.LongTensor(8)` and `torch.FloatTensor(1,1)`.
Then we go to [here ->> WARNING](https://github.com/torch/optim/blob/07fb9e0e22c1ff1a64613b24f0ba290e710aa5bd/ConfusionMatrix.lua#L69) for prediction and [here](https://github.com/torch/optim/blob/07fb9e0e22c1ff1a64613b24f0ba290e710aa5bd/ConfusionMatrix.lua#L91) for label.

Finally, we got `pred` with `torch.LongTensor(4)` but `label` with `torch.FloatTensor(1)`. 
As a result, `out of range` is thrown at [here](https://github.com/torch/optim/blob/07fb9e0e22c1ff1a64613b24f0ba290e710aa5bd/ConfusionMatrix.lua#L102)
x_x

***

Summary:
1. `batchAdd()` and `add()` works fine on `minibatch > 2`
2. `nn.Reshape(8)` will squeeze first dimension: `1x8x1x1 --> 8`, which is one of the cause of this bug
3. dimensional check at `batchAdd` is not all-covering, maybe mutual check of `preds` and `targets` should be considered.

***
Just report bug, if it's helpful to you, why not star repo? 
happy in hacking~ ;-)

**Comment by soumith** [comment]
Thanks for the bug report Fei. It does indeed look like a corner-case that is not covered.
